// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN5MeXLAoRSWeWbVUBSsBgy7e7APzN4RA',
    appId: '1:242501673693:web:b19b8bd84b48f846287134',
    messagingSenderId: '242501673693',
    projectId: 'bilgiyarismasi-93ece',
    authDomain: 'bilgiyarismasi-93ece.firebaseapp.com',
    storageBucket: 'bilgiyarismasi-93ece.firebasestorage.app',
    measurementId: 'G-4XNP9GDR79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9H6Uyerquc5D2bPYY77xVD51d02iAWRI',
    appId: '1:242501673693:android:455db468fa887503287134',
    messagingSenderId: '242501673693',
    projectId: 'bilgiyarismasi-93ece',
    storageBucket: 'bilgiyarismasi-93ece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiObCivjHrq6ZSSpaRt7jz8UuhS7zOioQ',
    appId: '1:242501673693:ios:89eaa4551b02471e287134',
    messagingSenderId: '242501673693',
    projectId: 'bilgiyarismasi-93ece',
    storageBucket: 'bilgiyarismasi-93ece.firebasestorage.app',
    iosBundleId: 'com.example.bilgiyarismasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiObCivjHrq6ZSSpaRt7jz8UuhS7zOioQ',
    appId: '1:242501673693:ios:89eaa4551b02471e287134',
    messagingSenderId: '242501673693',
    projectId: 'bilgiyarismasi-93ece',
    storageBucket: 'bilgiyarismasi-93ece.firebasestorage.app',
    iosBundleId: 'com.example.bilgiyarismasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN5MeXLAoRSWeWbVUBSsBgy7e7APzN4RA',
    appId: '1:242501673693:web:3febc0845bffee4f287134',
    messagingSenderId: '242501673693',
    projectId: 'bilgiyarismasi-93ece',
    authDomain: 'bilgiyarismasi-93ece.firebaseapp.com',
    storageBucket: 'bilgiyarismasi-93ece.firebasestorage.app',
    measurementId: 'G-V6E7B4MG2L',
  );

}